/* --------------------------------------------------------------------
 *
 * aGPIBIntDecls.h --
 *
 * 	'Asynchronous General Purpose Interface Bus' for Tcl.
 *
 *	This extension adds a new channel type to Tool Command Language
 * 	that allows for easy communication with devices plugged into
 * 	a GPIB bus.  Linux and Windows friendly.
 *
 *	Declarations of functions for the internal private
 *	aGPIB API. (auto-generated)
 *
 * --------------------------------------------------------------------
 *
 * Copyright (c) David Gravereaux <davygrvy@pobox.com>
 * 
 * See the file "license.terms" for information on usage and
 * redistribution of this file, and for a DISCLAIMER OF ALL
 * WARRANTIES.
 * 
 * --------------------------------------------------------------------
 * RCS: @(#) $Id: $
 * --------------------------------------------------------------------
 */

#ifndef INCL_aGPIBIntDecls_h_
#define INCL_aGPIBIntDecls_h_

/*
 * WARNING: This file is automatically generated by the $(TCLROOT)/tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the aGPIB.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

#ifndef InitializeGpibSubSystem_TCL_DECLARED
#define InitializeGpibSubSystem_TCL_DECLARED
/* 0 */
TCL_EXTERN(int)		InitializeGpibSubSystem _ANSI_ARGS_((
				Tcl_Interp * interp));
#endif

typedef struct AGPIBIntStubs {
    int magic;
    struct AGPIBIntStubHooks *hooks;

    int (*initializeGpibSubSystem) _ANSI_ARGS_((Tcl_Interp * interp)); /* 0 */
} AGPIBIntStubs;
TCL_EXTERNC AGPIBIntStubs *aGPIBIntStubsPtr;

#if defined(USE_AGPIB_STUBS) && !defined(USE_AGPIB_STUB_PROCS)

/*
 * Inline function declarations:
 */

#ifndef InitializeGpibSubSystem
#define InitializeGpibSubSystem \
	(aGPIBIntStubsPtr->initializeGpibSubSystem) /* 0 */
#endif

#endif /* defined(USE_AGPIB_STUBS) && !defined(USE_AGPIB_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* #ifndef INCL_aGPIBIntDecls_h_ */
