/* --------------------------------------------------------------------
 *
 * aGPIBDecls.h --
 *
 * 	'Asynchronous General Purpose Interface Bus' for Tcl.
 *
 *	This extension adds a new channel type to Tool Command Language
 * 	that allows for easy communication with devices plugged into
 * 	a GPIB bus.  Linux and Windows friendly.
 *
 *	Declarations of functions for the public external
 *	aGPIB API. (auto-generated)
 *
 * --------------------------------------------------------------------
 *
 * Copyright (c) David Gravereaux <davygrvy@pobox.com>
 *
 * See the file "license.terms" for information on usage and
 * redistribution of this file, and for a DISCLAIMER OF ALL
 * WARRANTIES.
 *
 * --------------------------------------------------------------------
 * RCS: @(#) $Id: $
 * --------------------------------------------------------------------
 */

#ifndef INCL_aGPIBDecls_h_
#define INCL_aGPIBDecls_h_

/*
 * WARNING: This file is automatically generated by the $(TCLROOT)/tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the aGPIB.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

#ifndef Agpib_Init_TCL_DECLARED
#define Agpib_Init_TCL_DECLARED
/* 0 */
TCL_EXTERN(int)		Agpib_Init _ANSI_ARGS_((Tcl_Interp * interp));
#endif
#ifndef Agpib_SafeInit_TCL_DECLARED
#define Agpib_SafeInit_TCL_DECLARED
/* 1 */
TCL_EXTERN(int)		Agpib_SafeInit _ANSI_ARGS_((Tcl_Interp * interp));
#endif
#ifndef Agpib_CreateChannel_TCL_DECLARED
#define Agpib_CreateChannel_TCL_DECLARED
/* 2 */
TCL_EXTERN(Tcl_Channel)	 Agpib_CreateChannel _ANSI_ARGS_((int board_index, 
				int pad, int sad));
#endif
#ifndef Agpib_OpenObjCmd_TCL_DECLARED
#define Agpib_OpenObjCmd_TCL_DECLARED
/* 3 */
TCL_EXTERN(int)		Agpib_OpenObjCmd _ANSI_ARGS_((ClientData notUsed, 
				Tcl_Interp * interp, Tcl_Size objc, 
				Tcl_Obj *CONST objv[]));
#endif
#ifndef Agpib_TriggerObjCmd_TCL_DECLARED
#define Agpib_TriggerObjCmd_TCL_DECLARED
/* 4 */
TCL_EXTERN(int)		Agpib_TriggerObjCmd _ANSI_ARGS_((ClientData notUsed, 
				Tcl_Interp * interp, Tcl_Size objc, 
				Tcl_Obj *CONST objv[]));
#endif
#ifndef Agpib_ClearObjCmd_TCL_DECLARED
#define Agpib_ClearObjCmd_TCL_DECLARED
/* 5 */
TCL_EXTERN(int)		Agpib_ClearObjCmd _ANSI_ARGS_((ClientData notUsed, 
				Tcl_Interp * interp, Tcl_Size objc, 
				Tcl_Obj *CONST objv[]));
#endif

typedef struct AGPIBStubHooks {
    struct AGPIBIntStubs *aGPIBIntStubs;
} AGPIBStubHooks;

typedef struct AGPIBStubs {
    int magic;
    struct AGPIBStubHooks *hooks;

    int (*agpib_Init) _ANSI_ARGS_((Tcl_Interp * interp)); /* 0 */
    int (*agpib_SafeInit) _ANSI_ARGS_((Tcl_Interp * interp)); /* 1 */
    Tcl_Channel (*agpib_CreateChannel) _ANSI_ARGS_((int board_index, int pad, int sad)); /* 2 */
    int (*agpib_OpenObjCmd) _ANSI_ARGS_((ClientData notUsed, Tcl_Interp * interp, Tcl_Size objc, Tcl_Obj *CONST objv[])); /* 3 */
    int (*agpib_TriggerObjCmd) _ANSI_ARGS_((ClientData notUsed, Tcl_Interp * interp, Tcl_Size objc, Tcl_Obj *CONST objv[])); /* 4 */
    int (*agpib_ClearObjCmd) _ANSI_ARGS_((ClientData notUsed, Tcl_Interp * interp, Tcl_Size objc, Tcl_Obj *CONST objv[])); /* 5 */
} AGPIBStubs;
TCL_EXTERNC AGPIBStubs *aGPIBStubsPtr;

#if defined(USE_AGPIB_STUBS) && !defined(USE_AGPIB_STUB_PROCS)

/*
 * Inline function declarations:
 */

#ifndef Agpib_Init
#define Agpib_Init \
	(aGPIBStubsPtr->agpib_Init) /* 0 */
#endif
#ifndef Agpib_SafeInit
#define Agpib_SafeInit \
	(aGPIBStubsPtr->agpib_SafeInit) /* 1 */
#endif
#ifndef Agpib_CreateChannel
#define Agpib_CreateChannel \
	(aGPIBStubsPtr->agpib_CreateChannel) /* 2 */
#endif
#ifndef Agpib_OpenObjCmd
#define Agpib_OpenObjCmd \
	(aGPIBStubsPtr->agpib_OpenObjCmd) /* 3 */
#endif
#ifndef Agpib_TriggerObjCmd
#define Agpib_TriggerObjCmd \
	(aGPIBStubsPtr->agpib_TriggerObjCmd) /* 4 */
#endif
#ifndef Agpib_ClearObjCmd
#define Agpib_ClearObjCmd \
	(aGPIBStubsPtr->agpib_ClearObjCmd) /* 5 */
#endif

#endif /* defined(USE_AGPIB_STUBS) && !defined(USE_AGPIB_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* #ifndef INCL_aGPIBDecls_h_ */
