/* ----------------------------------------------------------------------------
 * agpibDecls.h --
 *
 *	Declarations of functions in the platform dependent public
 *	Iocpsock API.
 *
 * ----------------------------------------------------------------------------
 * RCS: @(#) $Id: $
 * ----------------------------------------------------------------------------
 */

#ifndef INCL_agpibDecls_h_
#define INCL_agpibDecls_h_

/*
 * WARNING: This file is automatically generated by the $(TCLROOT)/tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the iocpsock.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/* !END!: Do not edit above this line. */

#endif /* #ifndef INCL_agpibDecls_h_ */
