/* ----------------------------------------------------------------------------
 * agpibStubInit.c --
 *
 *	This file contains the initializers for the aGPIB stub vectors.
 *
 * ----------------------------------------------------------------------------
 * RCS: @(#) $Id: iocpStubInit.c,v 1.9 2009/03/22 19:28:28 davygrvy Exp $
 * ----------------------------------------------------------------------------
 */

#include "aGPIBInt.h"

/*
 * WARNING: The contents of this file are automatically generated by the
 * $(ROOT)/tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the iocpsock.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

AGPIBIntStubs aGPIBIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
    InitializeGpibSubSystem, /* 0 */
};

static AGPIBStubHooks aGPIBStubHooks = {
    &aGPIBIntStubs
};

AGPIBStubs aGPIBStubs = {
    TCL_STUB_MAGIC,
    &aGPIBStubHooks,
    Agpib_Init, /* 0 */
    Agpib_SafeInit, /* 1 */
    Agpib_CreateChannel, /* 2 */
    Agpib_OpenObjCmd, /* 3 */
    Agpib_TriggerObjCmd, /* 4 */
};

/* !END!: Do not edit above this line. */
